image: python:3.10.12-slim

stages:
  - Static Analysis
  - Tests

black:
  stage: Static Analysis
  script:
    - pip install black==23.10.1
    - black . --check


djlint:
  stage: Static Analysis
  script:
    - pip install djlint==1.34.1
    - djlint static --check


pytest:
  stage: Tests
  script:
    - pip install -r requirements.txt
    - pytest .
