image: python:3.10.12-slim

stages:
  - Static Analysis

black:
  stage: Static Analysis
  script:
    - pip install black
    - black . --check


djlint:
  stage: Static Analysis
  script:
    - pip install djlint
    - djlint static --check
