name: CI

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    container: python:3.10.12-slim
    steps:
      - uses: actions/checkout@v3
      - name: Install black
        run: pip install black==23.10.1
      - name: Run black
        run: black . --check

  djlint:
    runs-on: ubuntu-latest
    container: python:3.10.12-slim
    needs: black
    steps:
      - uses: actions/checkout@v3
      - name: Install djlint
        run: pip install djlint==1.34.1
      - name: Run djlint
        run: djlint static --check

  pytest:
    runs-on: ubuntu-latest
    container: python:3.10.12-slim
    needs: [black, djlint]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run pytest
        run: pytest .

